### ISSUE TITLE
Delete form from card

### ISSUE THREAD

**Issue by watrall** [matrix-msu/kora#656]
currently, you have to go into the form to delete it.  Would be nice to have a "delete form" option right on the form card, along with the Edit Form Info, Form Records, Create New Records, and Go to Form buttons.

**Comment by fritosxii** [comment]
@watrall Currently, Form cards match layout of Project cards, which is why the trash icon is not present. Because Form is the main data structure, do we want a delete button to be easily accessible? Having the user required to go to edit Form and edit Project forces the user to be more intentional about deleting a Form (along with its records and data)

**Comment by watrall** [comment]
Hey, if someone deletes a form, its their problem.  Being able to delete a form quickly from the tile would speed situations where a user needed to delete multiple forms.
