### ISSUE TITLE
File Uploads Failing

### ISSUE THREAD

**Issue by cnufv** [matrix-msu/kora#803]
Kora is new to our institution and this is our first time setting it up. We do not have Cpanel so we are setting it up directly on a linux server with apache2 and PHP 7.4. I have followed the installation process and the app is working; well, mostly. File uploads are currently failing with the following error:

`[2021-06-17 22:16:12] production.ERROR: hash_file(app/tmpFiles/recordU1/test.jpg): failed to open stream: No such file or directory {"userId":1,"exception":"[object] (ErrorException(code: 0): hash_file(app/tmpFiles/recordU1/test.jpg): failed to open stream: No such file or directory at /var/www/html/app/KoraFields/FileTypeField.php:138)`

Checking the file upload location the test image in question is located in the directory /var/www/html/storage/app/tmpFiles/recordU1/ the file does seem to exist and is owned by the www-data user with the following permissions:

```
drwxrwxrwx 1 www-data www-data     0 Jun 17 22:16 .
drwxrwxrwx 1 root     root         0 Jun 17 20:38 ..
-rwxr-xr-x 1 www-data www-data 59324 Jun 17 22:16 test.jpg
drwxrwxrwx 1 www-data www-data     0 Jun 17 22:16 medium
drwxrwxrwx 1 www-data www-data     0 Jun 17 22:16 thumbnail
```

Please let me know if there are any configurations I may be missing.

**Edit:** Reverted to PHP 7.2.34 to see if it was some compatibility issue as mentioned in some other open issues however the issue still remains.

Thanks!

**Comment by norlander-ufv** [comment]
After some further poking around the issue seems to be related to relative pathing when used with the hash_file function exclusively; If I alter [line 109 of FileTypeField.php](https://github.com/matrix-msu/kora/blob/26507c382e6b9cbfdf6341660a2b2e6d60f5c045/app/KoraFields/FileTypeField.php#L109) to an absolute path to read `$tmpPath = '/var/www/html/storage/app/tmpFiles/recordU' . $uid;` the error does not occur however it also seems to skip the loading of files into the record all together. From there I tried changing [lines 137 and 138](https://github.com/matrix-msu/kora/blob/26507c382e6b9cbfdf6341660a2b2e6d60f5c045/app/KoraFields/FileTypeField.php#L137) as follows which seems to resolve the problem with files loading correctly into the record:

```
$tmpPath2 = '/var/www/html/storage/app/tmpFiles/recordU' . $uid;
$checksum = hash_file('sha256', $tmpPath2 . '/' . $fileName);
```

I am wondering if there is some path setting I need to set somewhere. If not I can use this workaround for the time being but without full knowledge of how the app works I worry there may be other uses of relative pathing elsewhere in the app that will only crop up once researchers begin working with the app.

**Comment by cnorlander** [comment]
Thanks, We will investigate an upgrade when possible. 

- Formerly cnufv
